Update cherry_pick_merge.yml

diff --git a/.github/workflows/cherry_pick_merge.yml b/.github/workflows/cherry_pick_merge.yml
--- a/.github/workflows/cherry_pick_merge.yml
+++ b/.github/workflows/cherry_pick_merge.yml
@@ -44,13 +44,14 @@ jobs:
         run: |
           # Push the changes to the feature branch
           git push origin ${{ github.event.inputs.feature-branch }}
+      - name: Install jq
+        run: sudo apt-get -y install jq
         
       - name: Create Pull Request
         env:
           PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
         run: |
           # Define the API endpoint and data for the pull request
-          API_URL=https://api.github.com/repos/${{ github.repository }}/pulls
           DATA='{
             "title": "Feature to Test PR",
             "head": "'"${{ github.event.inputs.feature-branch }}"'",
@@ -63,13 +64,18 @@ jobs:
           # Add debugging output
           #echo "API Response:"
           #echo "$PR_RESPONSE"
-          
-          # Check the response and handle errors
+
+      - name: Check PR Response
+        run: |
+          echo "Received response: $PR_RESPONSE"
           if [[ "$(echo "$PR_RESPONSE" | jq -r '.url')" == "$API_URL" ]]; then
-            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
-            echo "Pull request created successfully. PR Number: $PR_NUMBER"
+          PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
+          echo "Pull request created successfully. PR Number: $PR_NUMBER"
           else
-            echo "Failed to create pull request:"
-            echo "$PR_RESPONSE"
-            exit 1
+          echo "Failed to create pull request:"
+          echo "$PR_RESPONSE"
+          exit 1
           fi
+    env:
+      PR_RESPONSE: ${{ steps.create_pull_request.outputs.PR_RESPONSE }}
+      API_URL: https://api.github.com/repos/${{ github.repository }}/pulls
