Update cherry_pick_merge.yml

diff --git a/.github/workflows/cherry_pick_merge.yml b/.github/workflows/cherry_pick_merge.yml
--- a/.github/workflows/cherry_pick_merge.yml
+++ b/.github/workflows/cherry_pick_merge.yml
@@ -63,5 +63,19 @@ jobs:
           # Add debugging output
           #echo "API Response:"
           #echo "$PR_RESPONSE"
-          echo "::set-output name=PR_RESPONSE::$PR_RESPONSE"
-          #echo "{PR_RESPONSE}={$PR_RESPONSE}" >> $PR_RESPONSE
+          echo "PR_RESPONSE=$PR_RESPONSE" >> pr_response.env
+          
+      - name: Check PR Response
+        run: |
+          source pr_response.env
+          echo "Received response: $PR_RESPONSE"
+          if [[ "$(echo "$PR_RESPONSE" | jq -r '.url')" == "$API_URL" ]]; then
+            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
+            echo "Pull request created successfully. PR Number: $PR_NUMBER"
+          else
+            echo "Failed to create pull request:"
+            echo "$PR_RESPONSE"
+            exit 1
+          fi
+        env:
+          API_URL: https://api.github.com/repos/${{ github.repository }}/pulls
